// Generated by tools/compile_waypoints.py from Bot Warfare's mp_shipment_wp.csv
// (sha256 97e2ae04ab405e6efe5d1f692b11d703fc47e5224e0d576aa3d26dbdf56d3cc6). Waypoints by INeedGames / INeedBots, used with credit;
// see server/vendor/bot-warfare/LICENSE-NOTICE.md. Do not edit by hand.

jevWaypoints()
{
	w = [];
	w[0] = jevWaypoint((-1.7, 406.3, 192), "6 19 3 27 57", "stand");
	w[1] = jevWaypoint((-686, 278.79, 202.6), "3 2 28", "stand");
	w[2] = jevWaypoint((-669, 706.1, 193), "1 4 49 50", "stand");
	w[3] = jevWaypoint((-442.2, 384.5, 194.2), "1 4 0 16 27 28", "stand");
	w[4] = jevWaypoint((-127.28, 730.6, 193.6), "3 2 32", "stand");
	w[5] = jevWaypoint((208.3, 586.4, 197.1), "6 4 35 71", "stand");
	w[6] = jevWaypoint((450.1, 385.7, 192), "7 0 5 20 25", "stand");
	w[7] = jevWaypoint((401.8, 57.6, 192), "6 18 8 21 63 64", "stand");
	w[8] = jevWaypoint((455.4, -314, 193.2), "7 17 9 21 22", "stand");
	w[9] = jevWaypoint((175.7, -495.7, 192.6), "8 10 24 34 41", "stand");
	w[10] = jevWaypoint((-190.9, -591.4, 195.8), "13 11 9 36", "stand");
	w[11] = jevWaypoint((-556, -576.4, 191), "10 13 12 67", "stand");
	w[12] = jevWaypoint((-704.1, -302.7, 192.5), "11 14 68", "stand");
	w[13] = jevWaypoint((-342.8, -318, 197.7), "17 10 11 15", "stand");
	w[14] = jevWaypoint((-600.6, -110.9, 195.1), "15 12 30 45", "stand");
	w[15] = jevWaypoint((-476.7, -108.5, 192), "13 14 16 46 48", "stand");
	w[16] = jevWaypoint((-453.6, 68.1, 192), "3 18 15 28", "stand");
	w[17] = jevWaypoint((-3.1, -299.5, 192.7), "18 8 13 42", "stand");
	w[18] = jevWaypoint((2.67, 73.4, 192), "19 7 17 16 69", "stand");
	w[19] = jevWaypoint((1.2, 186.5, 193.4), "0 18 31", "stand");
	w[20] = jevWaypoint((689.9, 268.9, 192), "6 26 29 62", "stand");
	w[21] = jevWaypoint((518.984, -73.7115, 192.077), "7 8 33", "stand");
	w[22] = jevWaypoint((666.767, -411.292, 193.342), "23 8 33 66 74", "stand");
	w[23] = jevWaypoint((641.034, -594.69, 193.007), "24 22 65", "stand");
	w[24] = jevWaypoint((314.922, -568.756, 195.837), "23 9", "stand");
	w[25] = jevWaypoint((511.787, 726.464, 192.077), "6 26 35 55", "stand");
	w[26] = jevWaypoint((660.866, 688.142, 192.077), "25 20 56", "stand");
	w[27] = jevWaypoint((-185.714, 460.091, 192.077), "0 3 32", "stand");
	w[28] = jevWaypoint((-530.823, 242.686, 192.326), "1 3 16 47", "stand");
	w[29] = jevWaypoint((711.228, 25.2176, 201.125), "20 60 61", "stand");
	w[30] = jevWaypoint((-639.7, 137.441, 201.125), "14 43 44", "stand");
	w[31] = jevWaypoint((257.357, 148.73, 201.125), "19 58 59", "stand");
	w[32] = jevWaypoint((-156.114, 617.657, 194.681), "4 27 51", "stand");
	w[33] = jevWaypoint((656.389, -108.257, 192.558), "21 22 70", "stand");
	w[34] = jevWaypoint((172.465, -598.946, 193.226), "9 39", "stand");
	w[35] = jevWaypoint((252.991, 749.713, 197.697), "5 25 53", "stand");
	w[36] = jevWaypoint((-172.052, -492.845, 193.207), "10 37 72 73", "stand");
	w[37] = jevWaypoint((-75.1382, -499.556, 200.125), "38 36", "claymore");
	w[38] = jevWaypoint((-19.3432, -481.441, 192.077), "37", "crouch");
	w[39] = jevWaypoint((85.0988, -587.341, 200.125), "34 40", "claymore");
	w[40] = jevWaypoint((21.301, -610.073, 193.908), "39", "crouch");
	w[41] = jevWaypoint((149.762, -425.9, 195.321), "9", "claymore");
	w[42] = jevWaypoint((100.958, -233.485, 192.153), "17", "claymore");
	w[43] = jevWaypoint((-578.338, 184.612, 201.125), "30", "crouch");
	w[44] = jevWaypoint((-593.435, 90.8891, 201.125), "30", "claymore");
	w[45] = jevWaypoint((-723.435, -72.0006, 197.942), "14", "claymore");
	w[46] = jevWaypoint((-359.868, -62.7571, 192.077), "15", "claymore");
	w[47] = jevWaypoint((-338.009, 262.396, 192.344), "28", "crouch");
	w[48] = jevWaypoint((-337.125, -170.544, 192.077), "15", "crouch");
	w[49] = jevWaypoint((-718.728, 650.445, 192.845), "2", "grenade");
	w[50] = jevWaypoint((-645.978, 649.306, 193.743), "2", "grenade");
	w[51] = jevWaypoint((-75.5292, 597.058, 193.565), "32 52", "claymore");
	w[52] = jevWaypoint((0.635334, 602.359, 192.064), "51", "crouch");
	w[53] = jevWaypoint((151.737, 729.937, 195.165), "35 54", "claymore");
	w[54] = jevWaypoint((24.0866, 748.693, 192.077), "53", "crouch");
	w[55] = jevWaypoint((586.358, 730.315, 192.077), "25", "grenade");
	w[56] = jevWaypoint((662.354, 635.756, 192.077), "26", "grenade");
	w[57] = jevWaypoint((117.159, 353.125, 192.077), "0", "claymore");
	w[58] = jevWaypoint((269.892, 206.875, 201.125), "31", "crouch");
	w[59] = jevWaypoint((165.952, 157.587, 201.125), "31", "claymore");
	w[60] = jevWaypoint((659.141, 31.3728, 201.125), "29", "crouch");
	w[61] = jevWaypoint((668.763, 91.6303, 201.125), "29", "claymore");
	w[62] = jevWaypoint((581.503, 241.125, 192.077), "20", "claymore");
	w[63] = jevWaypoint((337.125, 164.429, 192.077), "7", "claymore");
	w[64] = jevWaypoint((337.125, 297.275, 192.077), "7", "crouch");
	w[65] = jevWaypoint((625.427, -520.984, 192.406), "23", "grenade");
	w[66] = jevWaypoint((666.143, -518.976, 192.354), "22", "grenade");
	w[67] = jevWaypoint((-645.523, -571.162, 191.226), "11", "grenade");
	w[68] = jevWaypoint((-670.623, -499.898, 187.333), "12", "grenade");
	w[69] = jevWaypoint((46.875, -43.8446, 192.077), "18", "claymore");
	w[70] = jevWaypoint((599.348, -68.9672, 192.077), "33", "claymore");
	w[71] = jevWaypoint((158.899, 529.62, 192.854), "5", "claymore");
	w[72] = jevWaypoint((-166.163, -437.371, 192.589), "36", "claymore");
	w[73] = jevWaypoint((-208.732, -457.476, 194.149), "36", "claymore");
	w[74] = jevWaypoint((706.721, -470.317, 192.339), "22", "grenade");
	return w;
}

jevWaypoint(origin, children, type)
{
	n = spawnStruct();
	n.origin = origin; n.type = type; n.children = [];
	if (children != "") { toks = strTok(children, " "); for (i = 0; i < toks.size; i++) n.children[i] = int(toks[i]); }
	return n;
}
