#!/usr/bin/env python3
"""Compile a Bot Warfare waypoint CSV into a GSC table for the Jev bot fixture (argument: map name, default mp_shipment).

Source: server/vendor/bot-warfare/scriptdata/waypoints/mp_shipment_wp.csv (INeedGames /
INeedBots, credit required; see server/vendor/bot-warfare/LICENSE-NOTICE.md). Row format
is "x y z,child indices,type,angles,,," after a leading count line. Children are the
waypoint indices this node links to. Output: game/jev_bot_waypoints.gsx.
"""
from __future__ import annotations

import hashlib
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MAP = sys.argv[1] if len(sys.argv) > 1 else "mp_shipment"
SOURCE = ROOT.parents[0] / f"vendor/bot-warfare/scriptdata/waypoints/{MAP}_wp.csv"
OUTPUT = ROOT / ("game/jev_bot_waypoints.gsx" if MAP == "mp_shipment" else f"game/jev_bot_waypoints_{MAP}.gsx")


def parse(text: str) -> list[dict]:
    lines = [line.strip() for line in text.splitlines() if line.strip()]
    count = int(lines[0])
    rows = lines[1:1 + count]
    if len(rows) != count:
        raise ValueError(f"expected {count} waypoints, found {len(rows)}")
    nodes = []
    for index, row in enumerate(rows):
        cols = row.split(",")
        x, y, z = (float(v) for v in cols[0].split())
        children = [int(v) for v in cols[1].split()] if cols[1].strip() else []
        kind = cols[2].strip() or "stand"
        for child in children:
            if not 0 <= child < count:
                raise ValueError(f"waypoint {index} links to {child} outside 0..{count - 1}")
        nodes.append({"index": index, "origin": (x, y, z), "children": children, "type": kind})
    return nodes


def emit(nodes: list[dict], digest: str) -> str:
    out = []
    out.append(f"// Generated by tools/compile_waypoints.py from Bot Warfare's {MAP}_wp.csv")
    out.append(f"// (sha256 {digest}). Waypoints by INeedGames / INeedBots, used with credit;")
    out.append("// see server/vendor/bot-warfare/LICENSE-NOTICE.md. Do not edit by hand.")
    out.append("")
    out.append("jevWaypoints()")
    out.append("{")
    out.append("\tw = [];")
    for node in nodes:
        x, y, z = node["origin"]
        children = " ".join(str(c) for c in node["children"])
        out.append(f"\tw[{node['index']}] = jevWaypoint(({x:g}, {y:g}, {z:g}), \"{children}\", \"{node['type']}\");")
    out.append("\treturn w;")
    out.append("}")
    out.append("")
    out.append("jevWaypoint(origin, children, type)")
    out.append("{")
    out.append("\tn = spawnStruct();")
    out.append("\tn.origin = origin; n.type = type; n.children = [];")
    out.append("\tif (children != \"\") { toks = strTok(children, \" \"); for (i = 0; i < toks.size; i++) n.children[i] = int(toks[i]); }")
    out.append("\treturn n;")
    out.append("}")
    out.append("")
    return "\n".join(out)


def main() -> int:
    text = SOURCE.read_text()
    digest = hashlib.sha256(text.encode()).hexdigest()
    nodes = parse(text)
    OUTPUT.write_text(emit(nodes, digest))
    links = sum(len(n["children"]) for n in nodes)
    kinds = sorted({n["type"] for n in nodes})
    print(f"{len(nodes)} waypoints, {links} links, types {kinds} -> {OUTPUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
